/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_siva_CreateDirectory */

#ifndef _Included_com_siva_CreateDirectory
#define _Included_com_siva_CreateDirectory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_siva_CreateDirectory
 * Method:    createDirectory
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_siva_CreateDirectory_createDirectory
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
