/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_siva_NtfsSet */

#ifndef _Included_com_siva_NtfsSet
#define _Included_com_siva_NtfsSet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_siva_NtfsSet
 * Method:    setPermission
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_siva_NtfsSet_setPermission
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
